import React, { useEffect, useState } from "react";
import * as XLSX from "xlsx";
import { AlertTriangle, Car, Download, Fuel, Home, Lock, Save, Settings, ShieldAlert, Smartphone, Trash2, Upload, X } from "lucide-react";

const APP_NAME="FDS Logbook", STORAGE_KEY="fds-logbook-v1", PIN_KEY="fds-logbook-pin-v1";
const ROLES=["OIC","OpA","CSO","TRO","SWO","DIM","HMEPO","FI","Other"];
const EMPTY={mileage:[],fuel:[],incidents:[],vehicles:[],locations:[]};
const today=()=>new Date().toISOString().slice(0,10);
const uid=()=>`${Date.now()}-${Math.random().toString(36).slice(2)}`;
function normalise(v){return {mileage:Array.isArray(v?.mileage)?v.mileage:[],fuel:Array.isArray(v?.fuel)?v.fuel:[],incidents:Array.isArray(v?.incidents)?v.incidents:[],vehicles:Array.isArray(v?.vehicles)?v.vehicles:[],locations:Array.isArray(v?.locations)?v.locations:[]}}
function load(){try{return normalise(JSON.parse(localStorage.getItem(STORAGE_KEY)||"{}"))}catch{return {...EMPTY}}}
function exportXlsx(filename,sheetName,headings,rows){
 const ws=XLSX.utils.aoa_to_sheet([headings,...rows]); ws["!autofilter"]={ref:ws["!ref"]};
 ws["!cols"]=headings.map((h,i)=>({wch:Math.min(40,Math.max(String(h).length+2,...rows.map(r=>String(r[i]??"").length+2)))}));
 const wb=XLSX.utils.book_new(); XLSX.utils.book_append_sheet(wb,ws,sheetName); XLSX.writeFile(wb,filename,{bookType:"xlsx",compression:true});
}
function download(name,text,type){const u=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement("a");a.href=u;a.download=name;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(u)}
function Field({label,required,hint,children}){return <label className="field"><span>{label}{required&&" *"}</span>{children}{hint&&<small>{hint}</small>}</label>}
function Notice({kind="info",children}){return <div className={`notice ${kind}`}>{children}</div>}
function View({title,intro,children}){return <section><h2>{title}</h2><p className="intro">{intro}</p><div className="panel stack">{children}</div></section>}
function Recent({rows,render}){return <div className="recent"><h3>Recent entries</h3>{rows.length?<div className="stack compact">{rows.slice(0,5).map(r=><div className="recent-row" key={r.id}>{render(r)}</div>)}</div>:<p className="muted">No records saved yet.</p>}</div>}
function SaveButton({onClick}){return <button className="btn primary" onClick={onClick}><Save size={18}/>Save entry</button>}

export default function App(){
 const [data,setData]=useState(load),[screen,setScreen]=useState("home"),[storageError,setStorageError]=useState(""),[message,setMessage]=useState(null);
 const [unlocked,setUnlocked]=useState(()=>!localStorage.getItem(PIN_KEY)),[pinEntry,setPinEntry]=useState("");
 const [installPrompt,setInstallPrompt]=useState(null),[installHelp,setInstallHelp]=useState(false);
 useEffect(()=>{try{localStorage.setItem(STORAGE_KEY,JSON.stringify(data));setStorageError("")}catch{setStorageError("FDS Logbook could not save to browser storage. Your latest changes may not persist.")}},[data]);
 useEffect(()=>{const h=e=>{e.preventDefault();setInstallPrompt(e);setInstallHelp(true)};addEventListener("beforeinstallprompt",h);if(/Android|iPhone|iPad|iPod/i.test(navigator.userAgent)&&!matchMedia("(display-mode: standalone)").matches)setInstallHelp(true);return()=>removeEventListener("beforeinstallprompt",h)},[]);
 const flash=(text,kind="success")=>{setMessage({text,kind});setTimeout(()=>setMessage(null),3500)};
 const patch=p=>setData(d=>({...d,...p}));
 const unlock=()=>{if(pinEntry===localStorage.getItem(PIN_KEY)){setUnlocked(true);setPinEntry("")}else flash("Incorrect PIN.","error")};
 if(!unlocked)return <main className="lock"><div className="panel stack"><h1><Lock/>FDS Logbook</h1><p className="muted">Enter your PIN to continue.</p><input type="password" inputMode="numeric" maxLength="8" value={pinEntry} onChange={e=>setPinEntry(e.target.value.replace(/\D/g,""))} onKeyDown={e=>e.key==="Enter"&&unlock()} placeholder="PIN"/><button className="btn primary" onClick={unlock}>Unlock</button></div></main>;
 const nav=[["home","Main menu",Home],["mileage","Mileage",Car],["fuel","Fuel",Fuel],["incidents","Incidents",ShieldAlert],["reports","Reports",Download],["settings","Settings",Settings]];
 return <div className="app"><header><button className="brand" onClick={()=>setScreen("home")}><b>FDS</b><span><strong>{APP_NAME}</strong><small>Personal, local and offline-first</small></span></button></header><main className="content">
 {storageError&&<Notice kind="error">{storageError}</Notice>}{message&&<Notice kind={message.kind}>{message.text}</Notice>}
 {installHelp&&<div className="install"><Smartphone/><div><strong>Add FDS Logbook to your home screen</strong><p>On iPhone or iPad, use Share then Add to Home Screen. On Android, use Install app or Add to Home screen from the browser menu.</p>{installPrompt&&<button className="btn primary" onClick={async()=>{await installPrompt.prompt();setInstallPrompt(null);setInstallHelp(false)}}>Install now</button>}</div><button className="icon-btn" aria-label="Dismiss" onClick={()=>setInstallHelp(false)}><X/></button></div>}
 {screen==="home"&&<HomeView go={setScreen} data={data}/>} {screen==="mileage"&&<Mileage data={data} patch={patch} flash={flash}/>} {screen==="fuel"&&<FuelLog data={data} patch={patch} flash={flash}/>} {screen==="incidents"&&<Incidents data={data} patch={patch} flash={flash}/>} {screen==="reports"&&<Reports data={data} flash={flash}/>} {screen==="settings"&&<SettingsView data={data} setData={setData} flash={flash}/>} </main>
 <nav>{nav.map(([k,l,I])=><button key={k} className={screen===k?"active":""} onClick={()=>setScreen(k)}><I size={20}/><span>{l}</span></button>)}</nav></div>
}
function HomeView({go,data}){const cards=[["mileage","Mileage Log","Record journeys and distances",Car,data.mileage.length],["fuel","Fuel Log","Record fuel costs and amounts",Fuel,data.fuel.length],["incidents","Incident Log","Record incident attendance",ShieldAlert,data.incidents.length],["reports","Reports","Download date-filtered Excel logs",Download,null],["settings","Settings","Backup, restore, PIN and deletion",Settings,null]];return <section><h2>Main menu</h2><p className="intro">Choose a log or manage your locally stored data.</p><div className="card-grid">{cards.map(([k,t,d,I,n])=><button className="menu-card" key={k} onClick={()=>go(k)}><I/><span><strong>{t}</strong><small>{d}</small></span>{n!==null&&<em>{n} records</em>}</button>)}</div></section>}
function Mileage({data,patch,flash}){const blank={date:today(),vehicle:"",startLocation:"",endLocation:"",use:"Business",start:"",end:"",distance:""};const [f,setF]=useState(blank),[error,setError]=useState("");const set=(k,v)=>setF(x=>({...x,[k]:v}));
 useEffect(()=>{const filled=[f.start,f.end,f.distance].filter(v=>v!=="").length;if(filled!==2)return;const s=f.start===""?null:+f.start,e=f.end===""?null:+f.end,d=f.distance===""?null:+f.distance;if(s!==null&&e!==null&&e>=s)set("distance",String(+(e-s).toFixed(2)));else if(s!==null&&d!==null&&d>=0)set("end",String(+(s+d).toFixed(2)));else if(e!==null&&d!==null&&d>=0&&e>=d)set("start",String(+(e-d).toFixed(2)))},[f.start,f.end,f.distance]);
 const save=()=>{setError("");if(!f.date||!f.vehicle.trim()||!f.startLocation.trim()||!f.endLocation.trim()||!f.use)return setError("Complete the date, vehicle, start location, end location and use.");if(f.vehicle.trim().length>8)return setError("Vehicle description must be 8 characters or fewer.");const nums=[f.start,f.end,f.distance].filter(v=>v!=="").map(Number);if(nums.some(v=>!Number.isFinite(v)||v<0))return setError("Mileage values must be valid non-negative numbers.");if(f.start!==""&&f.end!==""&&+f.end<+f.start)return setError("End odometer cannot be lower than start odometer.");if(f.start!==""&&f.end!==""&&f.distance!==""&&Math.abs((+f.end-+f.start)-+f.distance)>.01)return setError("The three mileage values do not agree.");const vehicle=f.vehicle.trim(),startLocation=f.startLocation.trim(),endLocation=f.endLocation.trim();patch({mileage:[{...f,id:uid(),vehicle,startLocation,endLocation},...data.mileage],vehicles:[...new Set([...data.vehicles,vehicle])],locations:[...new Set([...data.locations,startLocation,endLocation])]});setF(blank);flash("Mileage record saved on this device.")};
 return <View title="Mileage Log" intro="Enter zero, one, two or all three mileage values. Two valid values calculate the third automatically.">{error&&<Notice kind="error">{error}</Notice>}<div className="form-grid"><Field label="Date" required><input type="date" value={f.date} onChange={e=>set("date",e.target.value)}/></Field><Field label="Vehicle" required hint="Up to 8 characters"><input maxLength="8" list="vehicles" value={f.vehicle} onChange={e=>set("vehicle",e.target.value)} placeholder="e.g. CAR 1"/><datalist id="vehicles">{data.vehicles.map(v=><option key={v} value={v}/>)}</datalist></Field><Field label="Start location" required><input list="locations" value={f.startLocation} onChange={e=>set("startLocation",e.target.value)} placeholder="Start location"/></Field><Field label="End location" required><input list="locations" value={f.endLocation} onChange={e=>set("endLocation",e.target.value)} placeholder="End location"/><datalist id="locations">{data.locations.map(v=><option key={v} value={v}/>)}</datalist></Field><Field label="Use" required><select value={f.use} onChange={e=>set("use",e.target.value)}>{["Business","Commuting","Personal"].map(v=><option key={v}>{v}</option>)}</select></Field><Field label="Start odometer"><input type="number" min="0" step="0.1" value={f.start} onChange={e=>set("start",e.target.value)} placeholder="Optional"/></Field><Field label="End odometer"><input type="number" min="0" step="0.1" value={f.end} onChange={e=>set("end",e.target.value)} placeholder="Optional"/></Field><Field label="Trip distance"><input type="number" min="0" step="0.1" value={f.distance} onChange={e=>set("distance",e.target.value)} placeholder="Optional"/></Field></div><SaveButton onClick={save}/><Recent rows={data.mileage} render={r=>`${r.date} · ${r.vehicle} · ${r.startLocation} to ${r.endLocation}${r.distance!==""?` · ${r.distance} miles`:""}`}/></View>}
function FuelLog({data,patch,flash}){const blank={date:today(),amount:"",cost:""};const[f,setF]=useState(blank),[error,setError]=useState("");const save=()=>{setError("");if(!f.date||f.cost==="")return setError("Date and cost are required.");if(+f.cost<0||(f.amount!==""&&+f.amount<0))return setError("Amount and cost cannot be negative.");patch({fuel:[{...f,id:uid()},...data.fuel]});setF(blank);flash("Fuel record saved on this device.")};return <View title="Fuel Log" intro="Record a fuel purchase. Amount is optional.">{error&&<Notice kind="error">{error}</Notice>}<div className="form-grid"><Field label="Date" required><input type="date" value={f.date} onChange={e=>setF({...f,date:e.target.value})}/></Field><Field label="Amount"><input type="number" min="0" step="0.01" value={f.amount} onChange={e=>setF({...f,amount:e.target.value})} placeholder="Optional"/></Field><Field label="Cost (£)" required><input type="number" min="0" step="0.01" value={f.cost} onChange={e=>setF({...f,cost:e.target.value})} placeholder="0.00"/></Field></div><SaveButton onClick={save}/><Recent rows={data.fuel} render={r=>`${r.date} · £${Number(r.cost).toFixed(2)}${r.amount?` · ${r.amount}`:""}`}/></View>}
function Incidents({data,patch,flash}){const blank={date:today(),callTime:"",incidentNumber:"",role:"",arrived:"",mobileAvailable:"",stoodBy:""};const[f,setF]=useState(blank),[error,setError]=useState("");const set=(k,v)=>setF(x=>({...x,[k]:v}));const save=()=>{setError("");if(!f.date||!f.callTime||!f.role)return setError("Date, time of call and role are required.");if(!ROLES.includes(f.role))return setError("Select an approved role.");if(f.incidentNumber&&!/^\d+$/.test(f.incidentNumber))return setError("Incident number must contain numbers only.");patch({incidents:[{...f,id:uid()},...data.incidents]});setF(blank);flash("Incident record saved on this device.")};return <View title="Incident Log" intro="Date, time of call and role are required. All other details are optional.">{error&&<Notice kind="error">{error}</Notice>}<div className="form-grid"><Field label="Date" required><input type="date" value={f.date} onChange={e=>set("date",e.target.value)}/></Field><Field label="Time of call" required><input type="time" value={f.callTime} onChange={e=>set("callTime",e.target.value)}/></Field><Field label="Incident number"><input inputMode="numeric" value={f.incidentNumber} onChange={e=>set("incidentNumber",e.target.value.replace(/\D/g,""))} placeholder="Optional"/></Field><Field label="Role" required><select value={f.role} onChange={e=>set("role",e.target.value)}><option value="">Select role</option>{ROLES.map(v=><option key={v}>{v}</option>)}</select></Field><Field label="Time arrived incident"><input type="time" value={f.arrived} onChange={e=>set("arrived",e.target.value)}/></Field><Field label="Time mobile available"><input type="time" value={f.mobileAvailable} onChange={e=>set("mobileAvailable",e.target.value)}/></Field><Field label="Stood-by time"><input type="time" value={f.stoodBy} onChange={e=>set("stoodBy",e.target.value)}/></Field></div><SaveButton onClick={save}/><Recent rows={data.incidents} render={r=>`${r.date} · ${r.callTime} · ${r.role}${r.incidentNumber?` · Incident ${r.incidentNumber}`:""}`}/></View>}
function Reports({data,flash}){const[from,setFrom]=useState(""),[to,setTo]=useState(""),[error,setError]=useState("");const filtered=a=>a.filter(r=>(!from||r.date>=from)&&(!to||r.date<=to));const run=type=>{setError("");if(from&&to&&from>to)return setError("From date cannot be after To date.");const stamp=`${from||"all"}-to-${to||"all"}`;if(type==="mileage")exportXlsx(`FDS-Mileage-${stamp}.xlsx`,"Mileage",["Date","Vehicle","Start Location","End Location","Use","Start Odometer","End Odometer","Trip Distance"],filtered(data.mileage).map(r=>[r.date,r.vehicle,r.startLocation,r.endLocation,r.use,r.start,r.end,r.distance]));if(type==="fuel")exportXlsx(`FDS-Fuel-${stamp}.xlsx`,"Fuel",["Date","Amount","Cost (£)"],filtered(data.fuel).map(r=>[r.date,r.amount,r.cost]));if(type==="incidents")exportXlsx(`FDS-Incidents-${stamp}.xlsx`,"Incidents",["Date","Time of Call","Incident Number","Role","Time Arrived Incident","Time Mobile Available","Stood-by Time"],filtered(data.incidents).map(r=>[r.date,r.callTime,r.incidentNumber,r.role,r.arrived,r.mobileAvailable,r.stoodBy]));flash("Excel .xlsx report downloaded.")};return <View title="Reports" intro="Choose an optional date range, then download a genuine Excel .xlsx workbook.">{error&&<Notice kind="error">{error}</Notice>}<div className="form-grid"><Field label="From date"><input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></Field><Field label="To date"><input type="date" value={to} onChange={e=>setTo(e.target.value)}/></Field></div><div className="stack compact">{[["mileage","Mileage"],["fuel","Fuel"],["incidents","Incident"]].map(([k,l])=><button key={k} className="btn dark" onClick={()=>run(k)}><Download size={18}/>Download {l} Log</button>)}</div></View>}
function SettingsView({data,setData,flash}){const[file,setFile]=useState(null),[pin,setPin]=useState(""),[pinOn,setPinOn]=useState(()=>!!localStorage.getItem(PIN_KEY));const backup=()=>download(`FDS-Logbook-backup-${today()}.json`,JSON.stringify({app:APP_NAME,schemaVersion:1,exportedAt:new Date().toISOString(),data},null,2),"application/json");const restore=async()=>{if(!file)return flash("Choose a backup JSON file first.","error");try{const p=JSON.parse(await file.text());if(p.app!==APP_NAME||p.schemaVersion!==1||!p.data||![p.data.mileage,p.data.fuel,p.data.incidents].every(Array.isArray))throw 0;if(!confirm("Restore will replace all existing records on this device. Continue?"))return;setData(normalise(p.data));flash("Backup restored and saved on this device.")}catch{flash("This is not a valid FDS Logbook backup file.","error")}};const remove=k=>{if(confirm(`Delete all ${k} records? This cannot be undone.`)){setData(d=>({...d,[k]:[]}));flash(`${k[0].toUpperCase()+k.slice(1)} records deleted.`)}};const savePin=()=>{if(!/^\d{4,8}$/.test(pin))return flash("PIN must contain 4 to 8 numbers.","error");localStorage.setItem(PIN_KEY,pin);setPinOn(true);setPin("");flash("PIN lock enabled.")};return <View title="Settings" intro="Manage backup, restore, PIN protection and deletion."><div className="settings-grid"><div className="subpanel stack compact"><h3>Backup and restore</h3><button className="btn dark" onClick={backup}><Download/>Backup data as JSON</button><input type="file" accept="application/json,.json" onChange={e=>setFile(e.target.files?.[0]||null)}/><button className="btn" onClick={restore}><Upload/>Restore data</button></div><div className="subpanel stack compact"><h3>Optional PIN lock</h3>{pinOn?<><Notice>PIN lock is enabled.</Notice><button className="btn" onClick={()=>{localStorage.removeItem(PIN_KEY);setPinOn(false);flash("PIN lock removed.")}}>Remove PIN lock</button></>:<><input type="password" inputMode="numeric" maxLength="8" value={pin} onChange={e=>setPin(e.target.value.replace(/\D/g,""))} placeholder="Choose a 4 to 8 digit PIN"/><button className="btn primary" onClick={savePin}><Lock/>Enable PIN lock</button></>}</div><div className="subpanel danger stack compact"><h3>Delete log data</h3>{[["mileage","Mileage"],["fuel","Fuel"],["incidents","Incident"]].map(([k,l])=><button key={k} className="btn destructive" onClick={()=>remove(k)}><Trash2/>Delete {l} Log data</button>)}<button className="btn black" onClick={()=>{if(confirm("Delete ALL records and saved suggestions? This cannot be undone.")){setData({...EMPTY});flash("All logbook data deleted.")}}}><AlertTriangle/>Delete all</button></div></div></View>}
